#!/usr/bin/env python
'''Confirm the latest driver version

Usage:
	version <driver>

Options:
	-h,--help Show this message

Example:
	version igb
	version -h
'''
from docopt import docopt

def cli():
	argument = docopt(__doc__)
	print list[argument['<driver>']]
	
list = {
		'igb':			'5.3.0',
		'ixgb':			'4.4.0',
		'megaraid_sas':	'06.812.02.00',
		'pmc':			'',
		'qla2xxx':		'8.07.00.33.07.3',
		'lpfc':			'',
		'':				'',
		'':				'',
		   }

if __name__ == '__main__':
	cli()
